// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CharCounterController from "./char_counter_controller"
application.register("char-counter", CharCounterController)

import FormFilterController from "./form_filter_controller"
application.register("form-filter", FormFilterController)

import GenresController from "./genres_controller"
application.register("genres", GenresController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageLoaderController from "./image_loader_controller"
application.register("image-loader", ImageLoaderController)

import MainGenreController from "./main_genre_controller"
application.register("main-genre", MainGenreController)

import NewComicController from "./new_comic_controller"
application.register("new-comic", NewComicController)

import NewEpisodeController from "./new_episode_controller"
application.register("new-episode", NewEpisodeController)

import TagsController from "./tags_controller"
application.register("tags", TagsController)

import ViewerController from "./viewer_controller"
application.register("viewer", ViewerController)
