// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormFilterController from "./form_filter_controller"
application.register("form-filter", FormFilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageLoaderController from "./image_loader_controller"
application.register("image-loader", ImageLoaderController)

import NewComicController from "./new_comic_controller"
application.register("new-comic", NewComicController)

import NewEpisodeController from "./new_episode_controller"
application.register("new-episode", NewEpisodeController)
