require:
- rubocop-performance
- rubocop-rails
- rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
  - db/*
  - bin/*

# Db autocreates
Metrics:
  Exclude:
  - db/migrate/*

Style/Documentation:
  Exclude:
  - db/migrate/*
# -

Style/RedundantFetchBlock:
  Exclude:
  - config/puma.rb

Rails/I18nLocaleTexts:
  Exclude:
  - app/models/*

# Supports --autocorrect
Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  StyleGuide: "#consistent-string-literals"
  Enabled: true
  VersionAdded: '0.9'
  VersionChanged: '0.36'
  EnforcedStyle: double_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes
  ConsistentQuotesInMultiline: false
